config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get 'blog/index'
  get 'contact/index'
  get 'home/index'
  devise_for :users
  resources :products
  resources :details
  resources :orders
  resources :clients
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
   root "home#index"
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/client.rb
class Client < ApplicationRecord
    has_many :orders
    has_one_attached :avatar
end

app/models/detail.rb
class Detail < ApplicationRecord
    belongs_to :order
    belongs_to :product
end

app/models/order.rb
class Order < ApplicationRecord
    belongs_to :client
    belongs_to :detail
end

app/models/product.rb
class Product < ApplicationRecord
    has_many :details
    has_many_attached :images
end

app/models/role.rb
class Role < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/blog_controller.rb
class BlogController < ApplicationController
  def index
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  #before_action :authenticate_user!, :except => [:index]
  def index
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  #before_action :authenticate_user!
  before_action :set_order, only: %i[ show edit update destroy ]

  # GET /orders or /orders.json
  def index
    @orders = Order.all
  end

  # GET /orders/1 or /orders/1.json
  def show
  end

  # GET /orders/new
  def new
    @order = Order.new
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders or /orders.json
  def create
    @order = Order.new(order_params)

    respond_to do |format|
      if @order.save
        format.html { redirect_to order_url(@order), notice: "Order was successfully created." }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1 or /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to order_url(@order), notice: "Order was successfully updated." }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1 or /orders/1.json
  def destroy
    @order.destroy

    respond_to do |format|
      format.html { redirect_to orders_url, notice: "Order was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def order_params
      params.require(:order).permit(:date, :status, :total_price, :client_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blog_helper.rb
module BlogHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/details_helper.rb
module DetailsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Karu</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    
    <%= render 'shared/navbar' %>
    
 
   
      <%= yield %>
   
    <%= render 'shared/alert' %>
    <%= render 'shared/footer' %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
  </body>
</html>

app/views/shared/_alert.html.erb
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

app/views/shared/_footer.html.erb
    <footer class="container-fluid py-4 color-white" style="background-color: #073B4C;">
        <div class="row container mx-auto">
            <div class="col-12 col-sm-4 py-1">
                <h5 class=" py-2">Nosotros</h5>
                <p class="no-margin ">Lorem ipsum </p>
                <p class="no-margin ">Lorem ipsum </p>
                <p class="no-margin ">Lorem ipsum </p>
                <p class="no-margin ">Lorem ipsum </p>
            </div>
            <div class="col-12 col-sm-4 py-1">
                <h5 class="color-white py-2">Información</h5>
                <p class="no-margin ">Lorem ipsum </p>
                <p class="no-margin ">Lorem ipsum </p>
                <p class="no-margin ">Lorem ipsum </p>
                <p class="no-margin">Lorem ipsum </p>
            </div>
            <div class="col-12 col-sm-4 py-1">
                <h5 class=" py-2">Contáctanos</h5>
                <p class="no-margin ">Lorem ipsum </p>
                <p class="no-margin ">Lorem ipsum </p>
                <p class="no-margin ">Lorem ipsum </p>
                <p class="no-margin">Lorem ipsum </p>
            </div>
        </div>
        <!-- <footer class="container-fluid d-flex justify-content-around py-4" style="background-color: #0EAD69;"></footer> -->
        <!-- <hr>
        <div>
            <h2 class="logo">Karü</h2>
            <div>
                <a href=""><i class="fa-brands fa-instagram"></i></a>
                <a href=""><i class="fa-brands fa-facebook"></i></a>
            </div>
        </div> -->
    </footer>

app/views/shared/_navbar.html.erb
        <div class="top-bar py-1 d-flex justify-content-between px-2 dark-green-bg">
        <div class="">
            <a href=""><i class="fa-brands fa-instagram"></i></a>
            <a href=""><i class="fa-brands fa-facebook"></i></a>
            <a href=""><i class="fa-brands fa-linkedin"></i></a>
            <a href=""><i class="fa-solid fa-phone"></i></a>
            <a href=""><i class="fa-solid fa-envelope"></i></a>
        </div>
        <div>
            <a href=""><i class="fa-solid fa-user"></i></a>
            <a href=""><i class="fa-solid fa-cart-shopping"></i></a>  
             <% if user_signed_in? %>
                <li class="nav-item mx-2">
                    <%= button_to "Salir", destroy_user_session_path, method: :delete, data: { turbo: "false" } %>
                </li>
             <% else %>
            <a href=""><%= link_to "REGISTRARSE", new_user_registration_path, style: "color:white; text-decoration:none", class:'mx-2' %></a> 
            <a href=""><%= link_to "INICIAR SESIÓN", new_user_session_path, style: "color:white; text-decoration:none", class:'mx-3' %></a> 
            <% end %>
        </div>
    </div>
    
    <nav class="navbar navbar-expand-lg navbar-dark py-4 clear-green-bg">
        <div class="container-fluid">
            <a class="navbar-brand logo" href="#">Karü</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mx-auto mb-2 mb-lg-0">
                    <li class="nav-item mx-2">
                        <%=link_to 'INICIO', home_index_path, style: "color:white; text-decoration:none" %>
                    </li>
                    <li class="nav-item mx-2">
                        <%=link_to 'TIENDA', products_path, style: "color:white; text-decoration:none" %>
                    </li>
                    <li class="nav-item mx-2">
                        <%=link_to 'NUESTROS EMPRENDEDORES', blog_index_path, style: "color:white; text-decoration:none" %>
                    </li>
                    <li class="nav-item mx-2">
                        <%=link_to 'BLOG', blog_index_path, style: "color:white; text-decoration:none" %>
                    </li>
                    <li class="nav-item mx-2">
                        <%=link_to 'CONTACTO', contact_index_path, style: "color:white; text-decoration:none" %>
                    </li>
                    <li class="nav-item mx-2">
                        <%=link_to 'MI PERFIL', clients_path, style: "color:white; text-decoration:none" %>
                    </li>


                    <!--<li class="nav-item mx-2">
                        <%=link_to 'DETALLE PEDIDO', details_path, style: "color:white; text-decoration:none" %>
                    </li>
                     <li class="nav-item">
                        <a class="nav-link active" href="#">MI CUENTA</a>
                    </li> -->
                    <!-- <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Dropdown
                </a>
                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <li><a class="dropdown-item" href="#">Action</a></li>
                  <li><a class="dropdown-item" href="#">Another action</a></li>
                  <li><hr class="dropdown-divider"></li>
                  <li><a class="dropdown-item" href="#">Something else here</a></li>
                </ul>
              </li> -->

                    <!--<% if user_signed_in? %>
                        <li class="nav-item mx-2">
                            <%= button_to "Salir", destroy_user_session_path, method: :delete, data: { turbo: "false" } %>
                        </li>
                    <% else %>
                        <li class="nav-item mx-2">
                            <%= link_to "REGISTRARSE", new_user_registration_path, style: "color:white; text-decoration:none" %>
                        </li>
                        <li class="nav-item mx-2">
                            <%= link_to "INICIAR SESIÓN", new_user_session_path, style: "color:white; text-decoration:none" %>
                        </li>
                    <% end %>-->
                </ul>

                <form class="d-flex">
                    <input class="form-control me-2" type="search" placeholder="Buscar" aria-label="Search">
                    <button class="btn btn-outline-light" type="submit"><i
                            class="fa-solid fa-magnifying-glass"></i></button>
                </form>
            </div>
        </div>
    </nav>